### ISSUE TITLE
Finder Tags Import

### ISSUE THREAD

**Issue by rolandbley** [holtwick/collect#43]
Please explain your idea to make the app better:

When importing files with Finder Tags it would be nice if the Finder Tags are imported in collect.

App Version Info:
de.holtwick.mac.Collect@0.8.5+633 qEw8twhbRlKMTKCHVyRJHA

**Comment by holtwick** [comment]
That's a good idea. I'm already doing it in https://www.receipts-app.com/ so the code is there.

Thanks for the feedback. It is very much appreciated.

**Comment by holtwick** [comment]
Is implemented in the next release.
