### ISSUE TITLE
Drag'n'drop of more than one file causes freezing

### ISSUE THREAD

**Issue by rolandbley** [holtwick/collect#45]
Please describe how the error can be reproduced:

When dragging more than one file to collect the program freezes/the rainbow beach ball spins indefinitely. Reproducable under Mac OS 10.14.3.

App Version Info:
de.holtwick.mac.Collect@0.8.6+634 qEw8twhbRlKMTKCHVyRJHA

**Comment by holtwick** [comment]
Fixed in build 637
